### DISCUSSION TITLE
Disable unix-channels.toml

### DISCUSSION THREAD

**Discussion by vgalovic** [alexpasmantier/television#212] [Q&A] [answered]
Hello,

I installed television on my Linux computer, and I configured it with my own channels files. However, I don't like the `unix-channels.toml` channels since I don't use most of them, and I would prefer that `my-dotfiles` point to my own dotfiles rather than `.config`. Is it possible to turn off `unix-channels.toml`?

**Comment by baldwindavid** [comment]
I don't know about turning off channels, but you can overwrite a channel by adding a channel with the same name in your custom channels files. For example, my dotfiles are overwritten as...

```toml
[[cable_channel]]
name = "my-dotfiles"
source_command = 'fd -t f . $HOME/dotfiles'
preview_command = ':files:'
```
