### DISCUSSION TITLE
Symbolic links not followed

### DISCUSSION THREAD

**Discussion by gotcha** [alexpasmantier/television#273] [Q&A] [answered]
Am I right that `tv` does not follow links when searching ? If positive, how hard would it be to add that feature ?

**Comment by alexpasmantier** [comment, marked as answer]
> Am I right that tv does not follow links when searching ?

You are right indeed :-)

> If positive, how hard would it be to add that feature ?

Not too hard, you could simply create a custom cable channel along these lines:

```toml
[[cable_channel]]
name = "my-files"
source_command = "fd -t f -L ."  # you might want to remove the `-t f` here depending on your needs
preview_command = ":files:"
```

From the `fd` documentation:
```
-L, --follow
          By default, fd does not descend into symlinked directories. Using this flag, symbolic
          links are also traversed. Flag can be overridden with --no-follow.
```
