### DISCUSSION TITLE
Multiple channels for one command

### DISCUSSION THREAD

**Discussion by C4n4m1** [alexpasmantier/television#481] [Q&A] [answered]
Is it possible to associate multiple channels to an unique command in shell integration inside the config file ?
An example would be : 
"nvim" =  "files" + "dirs"

**Comment by lalvarezt** [comment, marked as answer]
how would the system know which of the two source and preview commands to use?
Instead you could create a new channel that does both, for example

```toml
[[cable_channel]]
name = "files-dirs-hidden"
source_command = "fd --hidden"
preview_command = "[ -f {} ] && bat --number --color=always {} || eza --long --group-directories-first --all --tree --level 2 --color=always {}"
```
