### DISCUSSION TITLE
Weird underlines in `eza` output when used as previewer in television (but not in shell)

### DISCUSSION THREAD

**Discussion by vgalovic** [alexpasmantier/television#537] [Q&A] [answered]
As I said in title, I get weird underlines on previewed items when using eza as a previewer for television, if I run same command as stand alone in shell, there is no underlines. Is there a way to remove underlines? 

Screenshot of preview in `tv`:
![Screenshot from 2025-06-11 16-19-22](https://github.com/user-attachments/assets/92c10c3e-de01-43b7-bd2c-f41d46a9a528)

Screenshot of `eza` run in fish shell:
![Screenshot from 2025-06-11 16-19-52](https://github.com/user-attachments/assets/b5d12a77-95a3-4485-8b77-323887ce7693)

My custom channel for directory:
```toml
[[cable_channel]]
name = "dirs"
source_command = "fd -t d -H -E .git -E .cache"
preview_command = "eza --long --git --all --color=always --icons=always {}"
```

Also, this is run on Linux Mint 22.1 Cinnamon and television is installed via cargo.
