### ISSUE TITLE
Allow `preview_title_position` config `top` | `bottom` 

### ISSUE THREAD

**Issue by yavorski** [alexpasmantier/television#143]
**Problem**
The current behavior of reversing the positions of input bar and preview title may not always align with user preferences. While this design choice might be beneficial in certain or personal workflows, it would be ideal to make this behavior configurable in order to allow  users to choose the desired positions of both.

**Feature request**
Introduce a configuration option for controlling the `preview_title_position`, just like `input_bar_position`.

**Examples**
```toml
input_bar_position = "top"
preview_title_position = "top"
```

**Additional context**
Thanks!

**Comment by alexpasmantier** [comment]
@yavorski is this what you had in mind ?

https://github.com/alexpasmantier/television/pull/144
## example
```toml
[ui]
input_bar_position = "top"
preview_title_position = "top"
```

<img width="2553" alt="Screenshot 2024-12-18 at 22 06 29" src="https://github.com/user-attachments/assets/6c9ac842-e383-42a8-bdf4-d48c7a826df3" />
