### ISSUE TITLE
Feature Request: Configuration of commands to run on selection

### ISSUE THREAD

**Issue by koopa1338** [alexpasmantier/television#16]
**Problem**
Currently you have to pipe the output to the command you want to handle (cd, xdg-open, etc.)

**Feature**
To prevent adding aliases for everything, it would be nice if it where possible to configure commands that handle the selection and to group them by channel. For example the `cd` command doesn't make sense in the files channel. A popup that lists all configured options with a fuzzy search would be amazing. 

The configuration I had in mind would look something like this:
```toml
[channels.file]
run_options = [ "xdg-open", "file", "rm" ]

[channels.git_repos]
run_options = [ "cd", "rm -r", "./local/bin/copy_commit_hash.sh" ]
```
