### ISSUE TITLE
Add actions to scroll the list by a page

### ISSUE THREAD

**Issue by wezm** [alexpasmantier/television#18]
**Problem**

I looked in https://github.com/alexpasmantier/television/blob/65bb26ec847e0d2caae49fbaeb3bffef90e094cd/crates/television/action.rs#L6 but did not find an action that would let me page through the result list, which ideally would be bound to Page-up/Page-down.

**Feature**

An action to page through the results list.

**Examples**

```toml
[keybindings.Channel]
pageup = "SelectNextPageEntry"
pagedown = "SelectPrevPageEntry"
```

**Additional context**

Here's how it works in `fzf`:

https://github.com/user-attachments/assets/d87a228c-e4be-49a5-a993-a211f1bdffc2
