### ISSUE TITLE
Option to enable hidden folders on Walkbuilder

### ISSUE THREAD

**Issue by jpcrs** [alexpasmantier/television#190]
Currently, it is not possible to use the "files" channel to search for files within hidden folders. Upon reviewing the code, Walkbuilder is utilizing the default value, and there is no option to configure it.  https://docs.rs/ignore/latest/src/ignore/walk.rs.html#730-736

It would be nice to have an argument to enable or disable it. Ideally, it should be possible to set arguments for a specific channel, but I think it's not currently supported?

**Comment by alexpasmantier** [comment]
You could solve this by creating a custom cable channel that includes hidden files (or maybe even override the default `files` channel with that if you like) like so:

```toml
# $CONFIG_FOLDER/television/my_cable_channels.toml
[[cable_channel]]
name = "hidden-files"
source_command = "fd --hidden"
preview_command = ":files:"
```

<img width="1053" alt="Screenshot 2025-01-09 at 14 23 50" src="https://github.com/user-attachments/assets/c75241c1-4ed6-4cac-bc04-76e35d161fca" />
