### ISSUE TITLE
[Windows]: Configuration not respecting Keymap changes

### ISSUE THREAD

**Issue by JustBarnt** [alexpasmantier/television#23]
Just wanna start with saying thanks for fixing that Environment Variable issue so quick! While this works flawlessly for me on my macbook, I keep find issues with Windows (which I use at work) so I wanna help get this up to speed for any future windows users! 😄 

**Description**
When changing the keymaps, such as removing `<C-n>/<C-p>` and re-assigning `SelectEntry` to `<C-j>/<C-k>` it does not seem like it actually unbinds the key, it updates the UI, but it still shows the default mappings.

![image](https://github.com/user-attachments/assets/64d01275-c324-4844-89b6-148d1d80b02f)

**Configuration**

```toml
# Ui settings
# ----------------------------------------------------------------------------
[ui]
# Whether to use nerd font icons in the UI
# This option requires a font patched with Nerd Font in order to properly
# display glyphs (see https://www.nerdfonts.com/ for more information)
use_nerd_font_icons = true
# How much space to allocate for the UI (in percentage of the screen)
# ┌───────────────────────────────────────┐
# │                                       │
# │            Terminal screen            │
# │    ┌─────────────────────────────┐    │
# │    │                             │    │
# │    │                             │    │
# │    │                             │    │
# │    │       Television UI         │    │
# │    │                             │    │
# │    │                             │    │
# │    │                             │    │
# │    │                             │    │
# │    └─────────────────────────────┘    │
# │                                       │
# │                                       │
# └───────────────────────────────────────┘
ui_scale = 80

# Previewers settings
# ----------------------------------------------------------------------------
[previewers.file]
# The theme to use for syntax highlighting
# A list of available themes can be found in the https://github.com/sharkdp/bat
# repository which uses the same syntax highlighting engine as television
theme = "Dracula"

# Keybindings
# ----------------------------------------------------------------------------
#
# Channel mode keybindings
[keybindings.Channel]
# Quit the application
esc = "Quit"
# Scrolling through entries
ctrl-j = "SelectNextEntry"
ctrl-k = "SelectPrevEntry"
# Scrolling the preview pane
ctrl-d = "ScrollPreviewHalfPageDown"
ctrl-u = "ScrollPreviewHalfPageUp"
# Select an entry
enter = "SelectEntry"
# Copy the selected entry to the clipboard
ctrl-y = "CopyEntryToClipboard"
# Toggle the remote control mode
ctrl-r = "ToggleRemoteControl"
# Toggle the send to channel mode
ctrl-s = "ToggleSendToChannel"

# Remote control mode keybindings
[keybindings.RemoteControl]
# Quit the application
esc = "Quit"
# Scrolling through entries
ctrl-j = "SelectNextEntry"
ctrl-k = "SelectPrevEntry"
# Select an entry
enter = "SelectEntry"
# Toggle the remote control mode
ctrl-r = "ToggleRemoteControl"

# Send to channel mode keybindings
[keybindings.SendToChannel]
# Quit the application
esc = "Quit"
# Scrolling through entries
ctrl-j = "SelectNextEntry"
ctrl-k = "SelectPrevEntry"
# Select an entry
enter = "SelectEntry"
# Toggle the send to channel mode
ctrl-s = "ToggleSendToChannel"


```

**Example**
1. Install `television` as instructed.
2. Update config with new keymaps
3. run television with whatever channel `tv files` 
4. Attempt to use new keymaps, they shouldn't work 
5. Look at `Results Navigation` in the TUI and you should see that it still has the original keymaps, and it may show your new keymaps as well (This last step has been very random, sometimes it shows both the keymaps I set, in this case it was <C-k> and <C-j> or sometimes it only shows one.)

**Expected behavior**
Television should respect the config and my custom keymaps should work, and the TUI should update accordingly and not show keymaps that aren't there.

**Actual behavior**
Doesn't respect the custom keymaps, and the TUI still shows the default maps and the new keymaps

**Environment**
- OS Name: Microsoft Windows 11 Pro
- OS Version: 10.0.22631 N/A Build 22631
- Rust version: rustc 1.80.1 (3f5fd8dd4 2024-08-06)
- Project version:
   television 0.4.21
   target triple: x86_64-pc-windows-msvc
   build: 1.80.1 (2024-11-14)
-Terminal:
   Wezterm: wezterm 20240812-215703-30345b36

**Additional context**
Any other context about the bug here.
