### ISSUE TITLE
sigint should exit television

### ISSUE THREAD

**Issue by llimllib** [alexpasmantier/television#272]
**Problem**
ctrl-c does not exit television

**Feature**
exit television on ctrl-c

**Additional context**
escape is good, but also I'm used to ctrl-c exiting programs and find it irritating that it doesn't exit television

I can't think of an interactive command that doesn't exit on ctrl-c except for REPLs like python, etc, where ctrl-c is handled as part of the programming environment; fzf exits on ctrl-c, and many others as well

**Comment by bob655** [comment]
I'm not certain this won't cause other problems, but I was able to get Ctrl-C to quit on Ubuntu by changing the `config.toml` file:

```toml
# ...
[keybindings.Channel]
# Quit the application
quit = ["esc", "ctrl-c"]
# ...
```
