### ISSUE TITLE
Builtin channels are used instead of custom channels when executed through the CLI and shell integration

### ISSUE THREAD

**Issue by MisterKartoffel** [alexpasmantier/television#275]
**Description**
Television release [0.9.1](https://github.com/alexpasmantier/television/releases/tag/0.9.1) merged PR #260, to allow custom channels to override builtins. This behavior is not reproducible if Television is launched through the terminal or with shell integration.

**Minimal configuration file excerpts**
  - `$XDG_CONFIG_HOME/television/config.toml`
```toml
[shell_integration.commands]
"ls" = "dirs"
"nvim" = "files"
```

  - `$XDG_CONFIG_HOME/television/custom-channels.toml`
```toml
[[cable_channel]]
name = "dirs"
source_command = "fd -t d -H . $HOME"
preview_command = "lsd -Al1 {}"

[[cable_channel]]
name = "files"
source_command = "fd -t f -H . $HOME"
preview_command = "bat -n --color=always {}"
```

**Video reproducing the issue**
- First example: shows `tv dirs` being executed, then changing to the `dirs` channel through Remote Control. Notice how there's no builtin `dirs` channel listed, yet the preview changes from builtin to `lsd`.
- Second example: `nvim` is completed using shell integration via `zsh`. The builtin files previewer is used, changing to `bat` when the `files` channel is selected via Remote Control.
- Third example: the function `nf`, described below, is executed. It contains a pipe with `tv files` as stdin, which also reproduces the issue listed in the previous example.

https://github.com/user-attachments/assets/71a06b9a-a200-4f03-ba4e-e8611e381ca8

*`nf` function as described in `$ZDOTDIR/.zshrc`*
```sh
function nf() {
  tv files | xargs -ro nvim
}
```

**Expected behavior**
The custom channels with same name as a builtin should be used for all interactions.

**Actual behavior**
Builtin channels are used instead, only being replaced when the custom channel is loaded via Remote Control.

**Environment**
 - OS: Arch Linux, kernel 6.12.9-arch1-1
 - Rust version: N/A
 - Project version: Television 0.9.2, build 1.83.0 (2025-01-10)
