### ISSUE TITLE
Piping a list of directories or files into Television breaks the previewer

### ISSUE THREAD

**Issue by MisterKartoffel** [alexpasmantier/television#276]
**Description**
When Television reads a list of directories or files received via stdin, the previewer only shows the absolute path to that directory or file, not the actual contents.

**Minimal configuration file excerpt**
- `$XDG_CONFIG_HOME/television/custom_channels.toml`
```toml
[[cable_channel]]
name = "dir"
source_command = "fd -t d -H . $HOME"
preview_command = "lsd -Al1 {}"

[[cable_channel]]
name = "file"
source_command = "fd -t f -H . $HOME"
preview_command = "bat -n --color=always {}"
```

**Video reproducing the issue**
- First example: shows a list of directories piped into both the builtin `dirs` channel and a custom `dir` channel with a custom previewer. Notice how both default to previewing the absolute path of the hovered directory.
- Second example: a list of files is piped into the `files` builtin and a custom `file` channel. Both previewers show the absolute path of the hovered file.

https://github.com/user-attachments/assets/47fb5910-56b6-422a-a879-7b5728a6ce13

**Expected behavior**
When receiving a list of arguments through stdin, Television should preview them with the configured previewer for the chosen channel.

**Actual behavior**
Instead, Television defaults to showing the absolute path for the hovered directory or file in the preview window.

**Environment**
- OS: Arch Linux, kernel 6.12.9-arch1-1
- Rust version: N/A
- Project version: Television 0.9.2, build 1.83.0 (2025-01-10)
