### ISSUE TITLE
Allow mapping C-e as a regular keybinding

### ISSUE THREAD

**Issue by freeo** [alexpasmantier/television#281]
**Description**
Tried to map a function to `ctrl-e` - it doesn't work.
Tried both scroll_preview_half_page_down and select_next_page so I suppose it must be something with ctrl-e itself.

tried it on alacritty, kitty, ghostty
tried zsh and bash

**Example**
config.toml:
``` toml
[keybindings.Channel]
scroll_preview_half_page_down = "ctrl-e" # doesn't work
scroll_preview_half_page_up = "ctrl-y"
```
Common vim bindings, ctrl-e is important...

**Expected behavior**
expected the preview to scroll down

**Actual behavior**
nothing

**Environment**
 OS: arch linux
 
television 0.9.2
target triple: x86_64-unknown-linux-gnu
build: 1.83.0 (2025-01-10)

**Additional context**
Thank you!
