### ISSUE TITLE
Deduplicating a channel

### ISSUE THREAD

**Issue by pickx** [alexpasmantier/television#347]
it would be useful to avoid duplicate entries in searches. for example, deduplicating `{zsh,bash,fish}-history` to only show the most recent occurrence of a command. for reference, I have [these options](https://unix.stackexchange.com/a/625366) set on zsh, but I'm still getting duplicates in Ctrl+R.

**Comment by alexpasmantier** [comment]
You might achieve something pretty similar with:

```toml
# Shell history
[[cable_channel]]
name = "zsh-history"
source_command = "cat ${HISTFILE:-${HOME}/.zsh_history} | cut -d\";\" -f 2- | sort | uniq -u"
```

the only minor painpoint being it won't conserve the original order, which shouldn't be a concern since you're then fuzzing on it and ranking results.
