### ISSUE TITLE
Shell custom keybind not workings

### ISSUE THREAD

**Issue by affanshahid** [alexpasmantier/television#430]
**Description**
I've rebound the shell history keybind but it is still triggered on ctrl+r.

**Expected behavior**
If I add the following to my config:

```toml
[shell_integration.keybindings]
"smart_autocomplete" = "ctrl-t"

"command_history" = "ctrl-["
```

ctrl+r should trigger my shell's native history lookup

**Actual behavior**
`tv` history lookup is triggered instead

**Environment**
 - OS: macOS Seqouia 15.3
 - Rust version: 1.85.0
 - Project version: 0.11.2

**Additional context**
It was working correctly before 0.11
