### ISSUE TITLE
[Design] Rework of the cable channels configuration system

### ISSUE THREAD

**Issue by alexpasmantier** [alexpasmantier/television#519]
### Discussed in https://github.com/alexpasmantier/television/discussions/518

<div type='discussions-op-text'>

<sup>Originally posted by **alexpasmantier** May 21, 2025</sup>
I'm currently putting some thought into the way to implement #16 and complete the migration to the #253 general idea.

With #497, #352, and #504, I'm starting to think this might be the occasion to migrate to a more expressive, extensible and modular cable channel format.

The current format consists of one or more big toml files that contain arrays of channel specs. I fear this will become less and less manageable over time as we increase the number of per-channel features and configuration options since we can't endlessly keep nesting toml tables.

I'm considering moving to something along the lines of:

- one `cable/` directory containing all channel specs
- one TOML file per channel inside that directory

```
TV_CONFIG_DIR/cable/
├── alias.toml
├── bash-history.toml
├── dirs.toml
├── docker-images.toml
├── env.toml
├── files.toml
└── etc.
```

where each TOML file would have a spec similar to:
```toml
[metadata]
name = "files"
description = "A channel to select files and directories"
requirements = ["fd", "bat"]

[source]
command = "fd -t f"
interactive = false
ansi = false

[preview]
command = "bat -n --color=always {}"
delimiter = " "
offset = 0
env = { "BAT_THEME" = "ansi" }

[ui]
layout = "landscape"
scale = 100
show_help = false
show_preview = true
input_position = "bottom"

[keymap]
quit = ["esc", "ctrl-c"]
select_next_entry = ["down", "ctrl-n", "ctrl-j"]
select_prev_entry = ["up", "ctrl-p", "ctrl-k"]
confirm_selection = "enter"

[[actions]]
name = "open in $EDITOR"
command = "$EDITOR {}"
mode = "become"          # "become" / "spawn" / "transform"

[[actions]]
name = "remove"
command = "rm {}"
mode = "spawn"

[[actions]]
name = "rename"
command = "read -p \"New name: \" new_name && mv {} $new_name"
mode = "spawn"
```

Any thoughts/remarks on this?

**Side note for the future:**
This could pave the way for proper cable “provider” plugins, which would simply involve adding collections of cable folders containing sets of channel specifications. For example, the Git cable provider would include all Git-related channels.</div>

**Comment by lalvarezt** [comment]
I really like this idea, it will open the door to a lot of customization and expressiveness.

With regards to source and output you could get some inspiration from 

Source processing
https://junegunn.github.io/fzf/reference/#--with-nthn-or-template
https://junegunn.github.io/fzf/reference/#--read0

Output processing
https://junegunn.github.io/fzf/reference/#--accept-nthn-or-template
https://junegunn.github.io/fzf/reference/#--print0

You could consider to standardize the use of delimiter for source,preview,output. The current implementation with offset only allows you to take one item from the list

Perhaps it would be easier to explain with an example, let's say I want to read a csv with some useful commands

```csv
A,B,command1,does this
A,C,command2,does that
```

The following will be shown on the list so it can be filtered

```text
[A] [B] command1
[A] [C] command2
```

The upon selection of the first item the preview would look like

```text
does this
```

When accepting the first item the output would look like

```text
command1
```

As for the config section it could look like 
Note: delimiter index comes from splitting the source

```toml
[metadata]
name = "cheatsheetA"
provider = ["cheatsheets"]
description = "Channel A to show all the boring stuff I don't remember"
requirements = []

[source]
command = 'cat "$USEFUL_CSV"'
interactive = false
ansi = false
read0 = false
delimiter = ","
template = "[{1}] [{2}] {3}"

[preview]
command = 'echo "{3}"'
env = {}
ansi = false
delimiter = ","

[output] 
delimiter = ","
template = "{3}"
ansi = false
print0 = false
```

Hope this makes it clearer
