### ISSUE TITLE
Toggle hidden items with Ctrl-H

### ISSUE THREAD

**Issue by vgalovic** [alexpasmantier/television#532]
**Problem**
When I type `cd` and hit <kbd>Ctrl-T</kbd> in the shell, I get a list of directories in my `$HOME`, but hidden ones like `.config` or `.local` don’t show up. That makes it hard to quickly jump into those folders.

**Feature**
It would be really useful to have a way to toggle hidden files and folders—kind of like how *Telescope* or *snacks.picker* does it in Neovim.

**Example**
So let’s say I type `cd` and press <kbd>Ctrl-T</kbd>—it’d be great if I could press something like <kbd>Ctrl-H</kbd> to include hidden items in the list. Especially for default channels like `:directory:` or `:files:`.

**Comment by lalvarezt** [comment]
I know it's not ideal but you could do ctrl-r and switch to another prepared channel that has hidden files as a workaround

**Comment by alexpasmantier** [comment]
This feature is coming up in the next release 😊

**Comment by alexpasmantier** [comment]
This is now possible by settings up multiple sources per-channel and cycling through them (bound to <kbd>ctrl-s</kbd> by default):
```toml
[metadata]
name = "files"
description = "A channel to select files and directories"
requirements = ["fd", "bat"]

[source]
command = ["fd -t f", "fd -t f -H"]

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }

[keybindings]
shortcut = "f1"
```
