### ISSUE TITLE
Theme overrides in config file

### ISSUE THREAD

**Issue by Ktoks** [alexpasmantier/television#560]
**Problem**
Customizing tv to fit the user's personal style requires users to rebuild from source code to modify theme.

**Feature**
I propose we add the same variables in the configuration to allow the theme colors to be changed there - letting the `themes/*.toml` files be defaults and the configuration to be overrides.

**Examples**
```toml
# The theme to use for the UI
# A list of builtin themes can be found in the `themes` directory of the television
# repository. You may also create your own theme by creating a new file in a `themes`
# directory in your configuration directory (see the `config.toml` location above).
theme = "gruvbox-dark"
background = "#000000"
```
![Image](https://github.com/user-attachments/assets/69be53fb-4c33-403d-9ed6-6e926716ab46)

**Additional context**
This could also get a lot of themes that we don't support added more easily - if you don't have to rebuild, it's easier to test.
