### ISSUE TITLE
Add support for multiple input-header entries

### ISSUE THREAD

**Issue by lalvarezt** [alexpasmantier/television#574]
**Problem**
With the current implementation if you have a channel that has multiple sources, like so

```toml
[metadata]
name = "files-dirs-hidden"
description = "A channel to select files and directories"
requirements = ["fd", "bat", "eza"]

[source]
command = ["fd --hidden", "fd --type d --hidden"]

[preview]
command = "[ -f {} ] && bat --number --color=always {} || eza --long --group-directories-first --all --tree --level 2 --color=always {}"
env = { BAT_THEME = "ansi" }

[keybindings]
shortcut = "f1"
```

Whenever you toggle, let's say with `ctrl-s`, there's no visual indication (other than the fact that the total entries changed, for example)

**Feature**
We could give the option to define multiple input header values, there would be a 1-1 match between the `input_header` and `source.command`.

Of course we could add validation if the entry is shorter, longer, etc.

**Examples**

example config file

```toml
[ui]
input_header = ["files-dir-hidden", "dir-hidden"]

[source]
command = ["fd --hidden", "fd --type d --hidden"]
```
